# Problem 2: Learning to implement Neural Network

## Gurmukhi Handwritten Digit Classification:
Gurmukhi is one of the popular
Indian scripts widely used in Indian state of Punjab. In this part of the assignment,
our goal is to develop a neural network solution (a simple NN, not a CNN) for classifying
Gurmukhi digits. We provide you Handwritten Gurmukhi digit dataset here:

Dataset link
Modify the code provided in here and a video tutorial here, and develop a robust
neural network to classify the Gurmukhi digits. Higher performance on test set will have bonus point. Briefly write your observation and submit your code so that we can evaluate your implementation at our end. (10 points)

In [36]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [37]:
# Importing all necessary Libraries
import os
from os.path  import join

import numpy as np
from array import array

import random
from shutil import copyfile
import struct



In [77]:
# Set the source directory of the dataset
src_dir = '/content/drive/MyDrive/Machine Learning Assignment03/Problem 02/train'

# Set the train-test split ratio
split_ratio = 0.8

# Create a list of all the image file paths and their corresponding labels
data = []
for label in os.listdir(src_dir):
    label_dir = os.path.join(src_dir, label)
    for img_file in os.listdir(label_dir):
        img_path = os.path.join(label_dir, img_file)
        data.append((img_path, label))

# Shuffle the data
random.shuffle(data)

# Split the data into train and test sets
split_index = int(len(data) * split_ratio)
train_data = data[:split_index]
Val_data = data[split_index:]

random.shuffle(train_data)
random.shuffle(Val_data)


print(f'Total number of images: {len(data)}')
print(f'Number of train images: {len(train_data)}')
print(f'Number of val images: {len(Val_data)}')

Total number of images: 1000
Number of train images: 800
Number of val images: 200


In [78]:
#Preprocess the images and labels
import random
import cv2

# Set the image size
img_height = 32
img_width = 32

X_train = []
Y_train = []
# Read all images and label in train folder
for img_path, label in train_data:
  img = cv2.imread(img_path)
  img = cv2.resize(img, (img_height, img_width))
  img = img / 255.0
  X_train.append(img)
  Y_train.append(label)

X_val = []
Y_val = []
# Read all images and label in test folder
for img_path, label in Val_data:
  img = cv2.imread(img_path)
  img = cv2.resize(img, (img_height, img_width))
  img = img / 255.0
  X_val.append(img)
  Y_val.append(label)


In [79]:
print(" size of training label ", len(Y_train))
print(" size of training data",len(X_train))


 size of training label  800
 size of training data 800


In [80]:
# Convert the data from list to numpy arrays

X_train = np.array(X_train)
Y_train = np.array(Y_train)

X_val = np.array(X_val)
Y_val = np.array(Y_val)

In [81]:
X_train.shape

(800, 32, 32, 3)

In [82]:
#Convert the labels to one-hot vectors

num_classes = len(np.unique(Y_train))
Y_train = np.eye(num_classes)[Y_train.astype('int32').flatten()]
Y_val = np.eye(num_classes)[Y_val.astype('int32').flatten()]

# Model Creation and Training using Keras Library

In [83]:
img_height, img_width = 32, 32
batch_size = 32
# import library
import os
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Flatten, Dropout
from keras.optimizers import Adam

# Define the model Neural Network
model = Sequential()
model.add(Flatten(input_shape=(img_height, img_width, 3)))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

# Compile the model
optimizer = Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

# Model Summary
print(model.summary())

# Train the model
epochs = 100
model.fit(X_train, Y_train,  epochs=epochs)

# Evaluate the model on the test data
loss, accuracy = model.evaluate(X_val, Y_val)

# Print the test accuracy
print('Validation accuracy:', accuracy)

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_7 (Flatten)         (None, 3072)              0         
                                                                 
 dense_14 (Dense)            (None, 128)               393344    
                                                                 
 dropout_7 (Dropout)         (None, 128)               0         
                                                                 
 dense_15 (Dense)            (None, 10)                1290      
                                                                 
Total params: 394,634
Trainable params: 394,634
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/100
25/25 [==============================] - 1s 5ms/step - loss: 1.9860 - accuracy: 0.3625
Epoch 2/100
25/25 [==============================] - 0s 5ms/step - loss: 0.9

In [45]:
# do prediction on the val dataset
prediction = model.predict(X_val)

7/7 [==============================] - 0s 3ms/step


In [46]:
# Predicted class value probability for one image 
prediction[10]

array([3.9626280e-09, 1.0273003e-06, 7.1448340e-11, 1.8592498e-08,
       1.5919090e-08, 6.0654576e-10, 5.1645771e-12, 9.9999887e-01,
       3.4178381e-08, 3.2267038e-09], dtype=float32)

In [47]:
# truth value for one image
Y_val[10]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])

In [86]:
test_dir = '/content/drive/MyDrive/Machine Learning Assignment03/Problem 02/val'

In [87]:
test_data = []
for label in os.listdir(test_dir):
    label_dir = os.path.join(test_dir, label)
    for img_file in os.listdir(label_dir):
        img_path = os.path.join(label_dir, img_file)
        test_data.append((img_path, label))

# Shuffle the data
random.shuffle(test_data)

In [88]:
test_data[0]

('/content/drive/MyDrive/Machine Learning Assignment03/Problem 02/val/1/11.tiff',
 '1')

In [89]:
# Set the image size
img_height = 32
img_width = 32

X_test = []
Y_test = []
# Read all images and label in train folder
for img_path, label in test_data:
  img = cv2.imread(img_path)
  img = cv2.resize(img, (img_height, img_width))
  img = img / 255.0
  X_test.append(img)
  Y_test.append(label)

In [90]:
# Convert the data from list to numpy arrays

X_test = np.array(X_test)
Y_test = np.array(Y_test)


In [91]:
#Convert the labels to one-hot vectors

num_classes = len(np.unique(Y_test))
Y_test = np.eye(num_classes)[Y_test.astype('int32').flatten()]

In [92]:
print(X_test[0])
Y_test[0]

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [0. 0. 0.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 ...

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])

In [93]:
# do prediction on the test dataset
prediction_test = model.predict(X_test)

6/6 [==============================] - 0s 3ms/step


In [96]:
# Evaluate the model on the test data
loss, accuracy = model.evaluate(X_test, Y_test)

# Print the test accuracy
print('Test dataset accuracy:', accuracy)

6/6 [==============================] - 0s 8ms/step - loss: 0.2503 - accuracy: 0.9494
Test dataset accuracy: 0.949438214302063


In [94]:
# Predicted class value probability for one image 
prediction_test[10]

array([5.7220112e-10, 1.8332888e-07, 2.7193934e-13, 3.3733235e-11,
       9.4685226e-10, 3.5594856e-09, 1.2580697e-06, 4.3097730e-12,
       1.4029610e-05, 9.9998444e-01], dtype=float32)

In [95]:
# truth value for one image
Y_test[10]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

### We can observe that Prediction is same as truth for image on test dataset

# Using Image DataGenerator Library

In [49]:
# import the necessary library
import os
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Flatten, Dropout
from keras.optimizers import Adam
from keras.preprocessing.image import ImageDataGenerator

# Set the train and test directories
train_dir = '/content/drive/MyDrive/Machine Learning Assignment03/Problem 02/train'
test_dir = '/content/drive/MyDrive/Machine Learning Assignment03/Problem 02/val'

# Set the image dimensions and batch size
img_height, img_width = 32, 32
batch_size = 32

# Create the data generators using ImageDatagenerator library
train_datagen = ImageDataGenerator(rescale=1./255, shear_range=0.2, zoom_range=0.2, horizontal_flip=True)
test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(train_dir, target_size=(img_height, img_width), batch_size=batch_size, class_mode='categorical')
test_generator = test_datagen.flow_from_directory(test_dir, target_size=(img_height, img_width), batch_size=batch_size, class_mode='categorical')

# Define the model
model = Sequential()
model.add(Flatten(input_shape=(img_height, img_width, 3)))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(len(train_generator.class_indices), activation='softmax'))

# Compile the model
optimizer = Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

# Model Summary
print(model.summary())

# Train the model
epochs = 10
model.fit(train_generator, epochs=epochs, validation_data=test_generator)

# Evaluate the model on the test data
loss, accuracy = model.evaluate(test_generator)

# Print the test accuracy
print('accuracy on Test data:', accuracy)

Found 1000 images belonging to 10 classes.
Found 178 images belonging to 10 classes.
Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_5 (Flatten)         (None, 3072)              0         
                                                                 
 dense_10 (Dense)            (None, 128)               393344    
                                                                 
 dropout_5 (Dropout)         (None, 128)               0         
                                                                 
 dense_11 (Dense)            (None, 10)                1290      
                                                                 
Total params: 394,634
Trainable params: 394,634
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/10
32/32 [==============================] - 4s 112ms/step - loss: 2.4144 - accurac

# Model Creation and Prediction without using Keras Library

In [98]:
#Flatten the images

X_train = X_train.reshape(X_train.shape[0], -1)
X_val = X_val.reshape(X_val.shape[0], -1)
X_test = X_test.reshape(X_test.shape[0], -1)

In [99]:
# Define the sigmoid and softmax activation functions
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

# Define the cross-entropy loss function
def cross_entropy_loss(y_true, y_pred):
    m = y_true.shape[0]
    cost = -1/m * np.sum(y_true * np.log(y_pred + 1e-8))
    return cost

# Define the ANN model
def init_params(input_size, hidden_size, output_size):
    W1 = np.random.randn(input_size, hidden_size) * 0.01
    b1 = np.zeros((1, hidden_size))
    W2 = np.random.randn(hidden_size, output_size) * 0.01
    b2 = np.zeros((1, output_size))
    return {"W1": W1, "b1": b1, "W2": W2, "b2": b2}

def forward_propagation(X, params):
    Z1 = np.dot(X, params["W1"]) + params["b1"]
    A1 = sigmoid(Z1)
    Z2 = np.dot(A1, params["W2"]) + params["b2"]
    A2 = softmax(Z2)
    return {"Z1": Z1, "A1": A1, "Z2": Z2, "A2": A2}

def back_propagation(X, Y, frwd_result, params, learning_rate):
    m = X.shape[0]
    dZ2 = frwd_result["A2"] - Y
    dW2 = 1/m * np.dot(frwd_result["A1"].T, dZ2)
    db2 = 1/m * np.sum(dZ2, axis=0, keepdims=True)
    dZ1 = np.dot(dZ2, params["W2"].T) * frwd_result["A1"] * (1 - frwd_result["A1"])
    dW1 = 1/m * np.dot(X.T, dZ1)
    db1 = 1/m * np.sum(dZ1, axis=0, keepdims=True)

    params["W1"] -= learning_rate * dW1
    params["b1"] -= learning_rate * db1
    params["W2"] -= learning_rate * dW2
    params["b2"] -= learning_rate * db2

def train(X, Y, input_size, hidden_size, output_size, num_epochs, learning_rate, batch_size):
    params = init_params(input_size, hidden_size, output_size)
    for i in range(num_epochs):
        for j in range(0, X.shape[0], batch_size):
            X_batch = X[j:j+batch_size]
            Y_batch = Y[j:j+batch_size]
            frwd_result = forward_propagation(X_batch, params)
            cost = cross_entropy_loss(Y_batch, frwd_result["A2"])
            back_propagation(X_batch, Y_batch, frwd_result, params, learning_rate)
            if j % 100 == 0:
                print("Cost after iteration number %i: %f" %(j, cost))
    return params


In [100]:
# Train the ANN model

input_size = img_height * img_width * 3  # input to be fed to input layer of the model
hidden_size = 256
output_size = num_classes # no the classes for classification
num_epochs = 100 # no of epoch for training
learning_rate = 0.01 # hyper parameter
# Define the batch size
batch_size = 32

params = train(X_train, Y_train, input_size, hidden_size, output_size, num_epochs, learning_rate, batch_size)

Cost after iteration number 0: 2.299990
Cost after iteration number 0: 2.294752
Cost after iteration number 0: 2.281945
Cost after iteration number 0: 2.266667
Cost after iteration number 0: 2.249475
Cost after iteration number 0: 2.229936
Cost after iteration number 0: 2.207411
Cost after iteration number 0: 2.181195
Cost after iteration number 0: 2.150563
Cost after iteration number 0: 2.114812
Cost after iteration number 0: 2.073326
Cost after iteration number 0: 2.025647
Cost after iteration number 0: 1.971575
Cost after iteration number 0: 1.911241
Cost after iteration number 0: 1.845157
Cost after iteration number 0: 1.774192
Cost after iteration number 0: 1.699488
Cost after iteration number 0: 1.622330
Cost after iteration number 0: 1.544003
Cost after iteration number 0: 1.465695
Cost after iteration number 0: 1.388426
Cost after iteration number 0: 1.313029
Cost after iteration number 0: 1.240154
Cost after iteration number 0: 1.170281
Cost after iteration number 0: 1.103753


In [101]:
# Evaluate the model on the validation dataset
frwd_result = forward_propagation(X_val, params)
predictions = np.argmax(frwd_result["A2"], axis=1)
accuracy = np.mean(predictions == np.argmax(Y_val, axis=1))
print("Test accuracy on validation data set: %.2f%%" %(accuracy * 100))

Test accuracy on validation data set: 97.00%


In [102]:
# Evaluate the model on the test dataset
frwd_result = forward_propagation(X_test, params)
predictions = np.argmax(frwd_result["A2"], axis=1)
accuracy = np.mean(predictions == np.argmax(Y_test, axis=1))
print("Test accuracy on test data set: %.2f%%" %(accuracy * 100))

Test accuracy on test data set: 93.82%
