#Problem 3: Chart Image Classification cation using CNN

# Problem statement: 
You have to develop a CNN-based classi
cation architecture for clas-
sifying a given chart image to one of 
ve chart classes, 

# Task 1:
Download the dataset from drive link given below.
Dataset link
Use the train and val images for training and validation in an appropriate ratio (e.g., 80% for
training and 20 % for validating). The CSV 
le contains corresponding labels for the images.

In [1]:
# Importing all necessary Libraries
import os
from os.path  import join
import struct
from array import array
import random
import cv2

import numpy as np
import pandas as pd


In [2]:
# Creating dataframe for the label dataframe
df = pd.read_csv("/content/drive/MyDrive/Machine Learning Assignment03/Problem 03/charts/train_val.csv")
df.columns

Index(['image_index', 'type'], dtype='object')

In [3]:
df['type']

0      vbar_categorical
1      vbar_categorical
2      vbar_categorical
3      vbar_categorical
4      vbar_categorical
             ...       
995            dot_line
996            dot_line
997            dot_line
998            dot_line
999            dot_line
Name: type, Length: 1000, dtype: object

In [4]:
# Map the categorical values to numerical codes
type_to_code = {'line':0, 'dot_line':1, 'pie':2, 'hbar_categorical':3, 'vbar_categorical':4}
df['type_code'] = df['type'].map(type_to_code)

In [5]:
# verifying column values 
df['type_code']

0      4
1      4
2      4
3      4
4      4
      ..
995    1
996    1
997    1
998    1
999    1
Name: type_code, Length: 1000, dtype: int64

In [6]:
# converting label dataframe to label list
label = df['type_code'].values.tolist()

In [8]:
label_dir = '/content/drive/MyDrive/Machine Learning Assignment03/Problem 03/charts/train_val'
filenames = os.listdir(label_dir)

In [9]:
# image_path_list = sorted(os.listdir(label_dir), key=lambda filename: int(filename.split('.')[0]))

sorted_filenames = sorted(filenames, key=lambda filename: int(filename.split('.')[0]))

In [10]:
src_dir = '/content/drive/MyDrive/Machine Learning Assignment03/Problem 03/charts/train_val'

In [11]:
full_img_path = []
for img_file in sorted_filenames:
    img_path = os.path.join(src_dir, img_file)
    full_img_path.append(img_path)

In [12]:
data = []
for img_file, class_label in zip(full_img_path, label):
    data.append((img_file, class_label))

In [13]:
len(data)

1000

In [14]:
data[1]

('/content/drive/MyDrive/Machine Learning Assignment03/Problem 03/charts/train_val/1.png',
 4)

In [15]:
split_ratio = 0.8
# Shuffle the data
random.shuffle(data)

# Split the data into train and test sets (80:20 ratio)
split_index = int(len(data) * split_ratio)
train_data = data[:split_index]
test_data = data[split_index:]

random.shuffle(train_data)
random.shuffle(test_data)

In [16]:
print(f'Total number of images: {len(data)}')
print(f'Number of train images: {len(train_data)}')
print(f'Number of test images: {len(test_data)}')

Total number of images: 1000
Number of train images: 800
Number of test images: 200


In [17]:
#Preprocess the images and labels
import random
import cv2

# Set the image size
img_height = 128
img_width = 128



X_train = []
Y_train = []
for img_path, label in train_data:
  img = cv2.imread(img_path)
  img = cv2.resize(img, (img_height, img_width))
  img = img / 255.0
  X_train.append(img)
  Y_train.append(label)

X_test = []
Y_test = []
for img_path, label in test_data:
  img = cv2.imread(img_path)
  img = cv2.resize(img, (img_height, img_width))
  img = img / 255.0
  X_test.append(img)
  Y_test.append(label)


In [18]:
# Convert the data to numpy arrays

X_train = np.array(X_train)
Y_train = np.array(Y_train)
X_test = np.array(X_test)
Y_test = np.array(Y_test)

In [19]:
Y_test.shape


(200,)

In [20]:
Y_test

array([2, 0, 0, 2, 4, 2, 3, 2, 3, 2, 1, 1, 2, 4, 1, 3, 4, 3, 4, 4, 2, 3,
       1, 3, 1, 3, 4, 4, 3, 2, 3, 0, 0, 1, 0, 4, 0, 4, 0, 2, 0, 3, 2, 2,
       0, 2, 0, 2, 1, 3, 1, 2, 0, 3, 1, 4, 3, 2, 2, 1, 4, 2, 1, 1, 3, 1,
       0, 4, 2, 2, 3, 3, 1, 3, 3, 1, 2, 4, 4, 4, 3, 0, 4, 1, 3, 1, 3, 3,
       4, 1, 1, 0, 2, 2, 4, 2, 4, 0, 4, 1, 0, 1, 2, 3, 3, 2, 3, 2, 2, 2,
       4, 3, 2, 2, 3, 0, 4, 4, 4, 2, 1, 4, 4, 3, 4, 0, 2, 1, 2, 1, 3, 2,
       2, 4, 3, 2, 0, 4, 2, 2, 4, 4, 1, 0, 4, 4, 4, 2, 2, 2, 2, 2, 4, 3,
       1, 2, 1, 2, 4, 2, 4, 3, 2, 3, 1, 2, 1, 3, 4, 4, 1, 1, 3, 0, 3, 4,
       0, 2, 1, 4, 3, 1, 4, 3, 1, 0, 0, 1, 0, 2, 1, 0, 4, 2, 1, 4, 0, 4,
       0, 1])

In [21]:
num_classes = len(np.unique(Y_train))
Y_train = np.eye(num_classes)[Y_train.astype('int32').flatten()]
Y_test = np.eye(num_classes)[Y_test.astype('int32').flatten()]

In [22]:
Y_test[0]

array([0., 0., 1., 0., 0.])

In [23]:
X_train.shape

(800, 128, 128, 3)

# Task 2:
Implement a two-layer Convolutional Neural Network, and calculate accuracy,
and loss and plot the obtained loss. Brie
y write your observation and submit your code so
that we can4 evaluate your implementation at our end.

# TWO Layered Convolutional Network

In [24]:
batch_size = 32

import os
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from keras.preprocessing.image import ImageDataGenerator
from keras.optimizers import Adam

# Define the input shape of the images
input_shape = (128, 128, 3)

# Define the number of output classes
num_classes = 5

# Define the model architecture [TWO Layered Convolutional Network]
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=input_shape),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(64, activation='relu'),
    Dense(num_classes, activation='softmax')
])

# Compile the model
optimizer = Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

# Model Summary
print(model.summary())

# Train the model
epochs = 10
model.fit(X_train, Y_train,  epochs=epochs)

# Evaluate the model on the test data
loss, accuracy = model.evaluate(X_test, Y_test)

# Print the test accuracy
print('Test accuracy:', accuracy)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 126, 126, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 63, 63, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 61, 61, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 30, 30, 64)       0         
 2D)                                                             
                                                                 
 flatten (Flatten)           (None, 57600)             0         
                                                                 
 dense (Dense)               (None, 64)                3

In [ ]:
prediction = model.predict(X_test)

7/7 [==============================] - 1s 167ms/step


In [ ]:
# Predicted class value probability for one image
prediction[0]


array([2.3861574e-11, 1.6932214e-10, 3.4869031e-11, 9.9999994e-01,
       4.7809357e-11], dtype=float32)

In [ ]:
# truth value
Y_test[0]

array([0., 0., 0., 1., 0.])

### Comparing above prediction and truth value/lable we can see our model is working fine [ Test accuracy: 0.9800000190734863 ]

# Multi layered Convolutional Network . 

Multi Layered CNN were performing even better than Two layered CNN .

In [ ]:
batch_size = 32

import os
import numpy as np

import keras
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from keras.preprocessing.image import ImageDataGenerator
from keras.optimizers import Adam

# Define the model architecture
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(128, 128, 3)))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(5, activation='softmax'))

# Compile the model
optimizer = Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

# Train the model
epochs = 10
model.fit(X_train, Y_train,  epochs=epochs)

# Evaluate the model on the test data
loss, accuracy = model.evaluate(X_test, Y_test)

# Print the test accuracy
print('Test accuracy:', accuracy)

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_2 (Conv2D)           (None, 126, 126, 32)      896       
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 63, 63, 32)       0         
 2D)                                                             
                                                                 
 conv2d_3 (Conv2D)           (None, 61, 61, 64)        18496     
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 30, 30, 64)       0         
 2D)                                                             
                                                                 
 conv2d_4 (Conv2D)           (None, 28, 28, 128)       73856     
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 14, 14, 128)     

## Task 3:
Finetune a pretrained network (e.g., AlexNet) for this task and report the results. 
### Using Pre-trained model VGG16

In [ ]:
# import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Flatten
from keras.applications import VGG16

# Define the number of output classes
num_classes = 5

# Load the pretrained VGG16 model
vgg16 = VGG16(weights='imagenet', include_top=False, input_shape=(128, 128, 3))

# Freeze all the layers in the pretrained model
for layer in vgg16.layers:
    layer.trainable = False

# Create a new model that includes the pretrained model and a new output layer
model = Sequential([
    vgg16,
    Flatten(),
    Dense(256, activation='relu'),
    Dense(num_classes, activation='softmax')
])

# Compile the model with categorical cross-entropy loss and Adam optimizer
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Print a summary of the model architecture
print(model.summary())

# Train the model
epochs = 10
model.fit(X_train, Y_train,  epochs=epochs)

# Evaluate the model on the test data
loss, accuracy = model.evaluate(X_test, Y_test)

# Print the test accuracy
print('Test accuracy:', accuracy)


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 vgg16 (Functional)          (None, 4, 4, 512)         14714688  
                                                                 
 flatten_3 (Flatten)         (None, 8192)              0         
                                                                 
 dense_6 (Dense)             (None, 256)               2097408   
                                                                 
 dense_7 (Dense)             (None, 5)                 1285      
                                                                 
Total params: 16,813,381
Trainable params: 2,098,693
Non-trainable params: 14,714,688
_________________________________________________________________
None
Epoch 1/10
25/25 [==============================] - 168s 7s/step - loss: 0.3493 - accuracy: 0.8988
Epoch 2/10
25/25 [==============================] - 167s 7s/st